# Generated by Django 5.0.1 on 2024-01-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent',
            new_name='Guardian',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parentId',
            new_name='guardianId',
        ),
    ]
