# Generated by Django 5.0.1 on 2024-01-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_remove_student_teacher_student_teacherid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardianId',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjectId',
        ),
        migrations.AddField(
            model_name='guardian',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.teacher'),
        ),
        migrations.CreateModel(
            name='Teacher_Subject_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('subjectId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.subject')),
                ('teacherId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class.teacher')),
            ],
        ),
    ]
