# Generated by Django 5.0.1 on 2024-01-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_remove_student_guardianid_remove_teacher_subjectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollNo',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
