# Generated by Django 5.0.1 on 2024-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_certificate',
            field=models.ImageField(default='', upload_to='Student/birth_certificate'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aadhar_card_image',
            field=models.ImageField(default='', upload_to='Teacher/aadhar'),
        ),
    ]
