# Generated by Django 5.0.1 on 2024-01-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_alter_student_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.IntegerField(default=0),
        ),
    ]
