# Generated by Django 5.0.1 on 2024-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
