# Generated by Django 5.0.1 on 2024-01-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0008_teacher_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='studentId',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacherId',
            new_name='teacher',
        ),
    ]
